INSERT INTO USER (ID, BIRTH_DATE, NAME) VALUES (10001, SYSDATE(), 'AB');
INSERT INTO USER (ID, BIRTH_DATE, NAME) VALUES (10002, SYSDATE(), 'Jill');
INSERT INTO USER (ID, BIRTH_DATE, NAME) VALUES (10003, SYSDATE(), 'Jam');