INSERT INTO USER (ID, BIRTH_DATE, NAME) VALUES (1, SYSDATE(), 'AB');
INSERT INTO USER (ID, BIRTH_DATE, NAME) VALUES (2, SYSDATE(), 'Jill');
INSERT INTO USER (ID, BIRTH_DATE, NAME) VALUES (3, SYSDATE(), 'Jam');