INSERT INTO USER (ID, BIRTH_DATE, NAME) VALUES (10001, SYSDATE(), 'AB');
INSERT INTO USER (ID, BIRTH_DATE, NAME) VALUES (10002, SYSDATE(), 'Jill');
INSERT INTO USER (ID, BIRTH_DATE, NAME) VALUES (10003, SYSDATE(), 'Jam');

INSERT INTO POST (ID, DESCRIPTION, USER_ID) VALUES (11001, 'My First Post', 10001);
INSERT INTO POST (ID, DESCRIPTION, USER_ID) VALUES (11002, 'My Second Post', 10001);