INSERT INTO CURRENCY_EXCHANGE (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT)
VALUES (10001, 'USD', 'INR', 65, '');
INSERT INTO CURRENCY_EXCHANGE (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT)
VALUES (10002, 'EUR', 'INR', 75, '');
INSERT INTO CURRENCY_EXCHANGE (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT)
VALUES (10003, 'AUD', 'INR', 25, '');